# Generated by the Chameleon Platform

source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '3.2.19'
gem 'unicorn', '4.8.3'
gem 'dalli', '2.5.0'
gem 'kgio', '2.7.4'
gem 'devise', '2.1.2'
gem 'apipie-rails', '0.0.13'
gem 'redcarpet', '2.2.2'
gem 'rest-client', '1.6.7'
gem 'oauth', git: 'git://github.com/AnyPresence/oauth-ruby.git'
gem 'rack-cors', '0.2.8', require: 'rack/cors'

gem 'haml', '3.1.7'
gem 'simple_form', '2.0.4'
gem 'compass-rails', '1.0.3'
gem 'compass-recipes', '0.3.0'
gem 'sass-rails', '3.2.5'
gem 'bootstrap-sass', '3.1.1.0'
gem 'font-awesome-rails', '4.0.3.1'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '2.0.3'
gem 'jquery_mobile_rails', '1.2.0'


# Datasource adapter gems
gem 'mongoid', '3.1.4'
gem 'mongoid_session_store', tag: 'v2.1.1', git: 'git://github.com/AnyPresence/mongoid_session_store.git'
DM_VERSION = '~> 1.2.0'
gem 'dm-core', '1.2.1'
gem 'dm-rails', DM_VERSION
gem 'dm-serializer', DM_VERSION
gem 'dm-validations', DM_VERSION
gem 'dm-accepts_nested_attributes', '1.1.0', git: 'git://github.com/snusnu/dm-accepts_nested_attributes.git'
gem 'dm-aggregates', DM_VERSION
gem 'dm-do-adapter', DM_VERSION
gem 'dm-migrations', tag: 'v1.2.1', git: 'git://github.com/AnyPresence/dm-migrations.git'
gem 'dm-constraints', DM_VERSION
gem 'savon', '~> 2.2.0'
gem 'dm-soap-adapter', tag: 'v0.0.3', git: 'git://github.com/AnyPresence/dm-soap-adapter.git'

# Custom gem dependencies


gem 'redis', '3.0.4'
gem 'resque', '1.25.0'

# Gems for extensions that are rails engine gems.
gem 'liquid'
gem 'kaminari', '~> 0.14.1'

group :development do
  gem 'foreman', '0.60.2'
end

group :test do
  gem 'shoulda', '~> 3.0.1'
  gem 'mocha', '~> 0.13.3', require: false
  gem 'capybara', '~> 2.1.0'
  gem 'poltergeist', '~> 1.3.0'
  gem 'launchy'
end
